CREATE TABLE IF NOT EXISTS news (
    Id BIGSERIAL PRIMARY KEY NOT NULL,
    Title VARCHAR(100) NOT NULL,
    Content VARCHAR(255) NOT NULL,
    Created TIMESTAMP NULL,
    Updated TIMESTAMP NULL,
    Author_Id BIGINT NULL,

    CONSTRAINT FK_NEWS_AUTHOR FOREIGN KEY (Author_Id) REFERENCES authors(Id) ON DELETE SET NULL
);