CREATE TABLE IF NOT EXISTS news_tags (
    News_Id BIGINT NULL,
    Tag_Id BIGINT NULL,

    CONSTRAINT FK_TAG_NEWS FOREIGN KEY (News_Id) REFERENCES news(Id),
    CONSTRAINT FK_NEWS_TAG FOREIGN KEY (Tag_Id) REFERENCES tags(Id)
);