CREATE TABLE IF NOT EXISTS comments (

    Id BIGSERIAL PRIMARY KEY NOT NULL,
    Content VARCHAR(255) NOT NULL,
    Created TIMESTAMP NULL,
    Updated TIMESTAMP NULL,
    News_Id BIGINT NULL,

    CONSTRAINT FK_COMMENTS_NEWS FOREIGN KEY (News_Id) REFERENCES news(Id) ON DELETE SET NULL
);