spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/news-management-dev
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

flyway:
  url: jdbc:postgresql://localhost:5432
  schemas: news-management-dev
  user: root
  password: root

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000